---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# rspmapi

<!-- badges: start -->
<!-- badges: end -->



## Installation

You can install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("remotes")
remotes::install_github("JosiahParry/rspmapi")
```
## Example

List all repositories. 

```{r warning=FALSE, message=FALSE}
library(rspmapi)
library(tidyverse)

get_repos()
```

List system dependencies for a package.

```{r}
get_package_sysreqs("stringr", distribution = "redhat") 

(stringr_deps <- get_package_sysreqs("stringr", distribution = "ubuntu"))
```

```{r}
stringr_deps %>% 
  unnest(dependencies) %>% 
  # system_reqs is stored in a list because sometimes there is > 1 req per package 
  transmute(system_reqs = unlist(system_reqs))
```

Get system requirements for the entire repository.

```{r}
# default distro is ubuntu
(repo_sysreqs <- get_repo_sysreqs(1))
```
Get the install scripts for your Linux distribution

```{r}
repo_sysreqs %>% 
  slice(1:3) %>% 
  pull(install_scripts)
```

